---@diagnostic disable: undefined-global
return {
	s("template{calc}", {

		t({"", "\\documentclass[paper=a4, fontsize=11pt]{scrartcl}"}),
		t({"", ""}),
		t({"","\\usepackage[T1]{fontenc}"}),
		t({"","\\usepackage{fourier}"}),
		t({"","\\usepackage[italian]{babel}"}),
		t({"","\\usepackage{amsmath,amsfonts,amsthm}"}),
		t({"","\\usepackage{fancyhdr} "}),
		t({"", ""}),
		t({"","\\pagestyle{fancyplain}"}),
		t({"", ""}),
		t({"","\\fancyhead{}"}),
		t({"","\\fancyfoot[L]{}"}),
		t({"","\\fancyfoot[C]{}"}),
		t({"","\\fancyfoot[R]{\\thepage}"}),
		t({"", ""}),
		t({"","\\renewcommand{\\headrulewidth}{0pt} "}),
		t({"","\\renewcommand{\\footrulewidth}{0pt}"}),
		t({"", ""}),
		t({"","\\setlength{\\headheight}{13.6pt}"}),
		t({"","\\numberwithin{equation}{section}"}),
		t({"","\\newcommand{\\horrule}[1]{\\rule{\\linewidth}{#1}}"}),
		t({"", ""}),
		t({"","\\title{	"}),
		t({"","\\normalfont \\normalsize "}),
		t({"","\\horrule{0.5pt} \\\\[0.4cm]"}),
		t({"","\\huge "}), i(1, "Titolo"), t({" \\\\"}),
		t({"","\\horrule{2pt} \\\\[0.5cm]"}),
		t({"","\\author{"}), i(2, "Nome"), t({"}"}),
		t({"", "}"}),
		t({"", ""}),
		t({"","\\begin{document}"}),
		t({"", "\\maketitle"}),
		t({"", ""}),
		t({"",""}), i(0),
		t({"", ""}),
		t({"","\\end{document}"}),
	})
}
